import React from 'react';
import './TimeTable.css';

const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
const hours = ['8:00 AM', '8:50 AM', '9:40 AM', '10:30 AM', '11:20 AM', '12:10 PM', '1:00 PM', '1:50 PM', '2:40 PM', '3:30 PM', '4:20 PM', '5:10 PM'];
// const hours = ['8-8:50', '8:50-9:40', '9:40-10:30', '10:30-11:20', '11:20-12:10', '12:10-1', '1-1:50', '1:50-2:40', '2:40-3:30', '3:30-4:20', '4:20-5:10', '5:10-6'];

const events = [{'day': 'Monday',
  'hour': '1:00 PM',
  'subjectName': 'Theory of Computation',
  'subjectCode': 'UCS701',
  'venue': 'LT402',
  'color': '#FFD700'},
 {'day': 'Wednesday',
  'hour': '8:00 AM',
  'subjectName': 'Theory of Computation',
  'subjectCode': 'UCS701',
  'venue': 'LT402',
  'color': '#FFD700'},
 {'day': 'Friday',
  'hour': '1:00 PM',
  'subjectName': 'Theory of Computation',
  'subjectCode': 'UCS701',
  'venue': 'LT402',
  'color': '#FFD700'},
 {'day': 'Monday',
  'hour': '1:50 PM',
  'subjectName': 'Computer Graphics',
  'subjectCode': 'UCS505',
  'venue': 'LT402',
  'color': '#FFD700'},
 {'day': 'Tuesday',
  'hour': '3:30 PM',
  'subjectName': 'Computer Graphics',
  'subjectCode': 'UCS505',
  'venue': 'LT402',
  'color': '#FFD700'},
 {'day': 'Friday',
  'hour': '1:50 PM',
  'subjectName': 'Computer Graphics',
  'subjectCode': 'UCS505',
  'venue': 'LT402',
  'color': '#FFD700'},
 {'day': 'Monday',
  'hour': '2:40 PM',
  'subjectName': 'Microprocessor-Based Systems Design',
  'subjectCode': 'UCS617',
  'venue': 'LT402',
  'color': '#FFD700'},
 {'day': 'Tuesday',
  'hour': '4:20 PM',
  'subjectName': 'Microprocessor-Based Systems Design',
  'subjectCode': 'UCS617',
  'venue': 'LT402',
  'color': '#FFD700'},
 {'day': 'Friday',
  'hour': '2:40 PM',
  'subjectName': 'Microprocessor-Based Systems Design',
  'subjectCode': 'UCS617',
  'venue': 'LT402',
  'color': '#FFD700'},
 {'day': 'Tuesday',
  'hour': '9:40 AM',
  'subjectName': 'OPTIMIZATION TECHNIQUES',
  'subjectCode': 'UMA035',
  'venue': 'LT402',
  'color': '#FFD700'},
 {'day': 'Wednesday',
  'hour': '8:50 AM',
  'subjectName': 'OPTIMIZATION TECHNIQUES',
  'subjectCode': 'UMA035',
  'venue': 'LT402',
  'color': '#FFD700'},
 {'day': 'Thursday',
  'hour': '12:10 PM',
  'subjectName': 'OPTIMIZATION TECHNIQUES',
  'subjectCode': 'UMA035',
  'venue': 'LT402',
  'color': '#FFD700'},
 {'day': 'Tuesday',
  'hour': '10:30 AM',
  'subjectName': 'INNOVATION AND ENTREPRENEURSHIP',
  'subjectCode': 'UTA025',
  'venue': 'LT402',
  'color': '#FFD700'},
 {'day': 'Wednesday',
  'hour': '5:10 PM',
  'subjectName': 'Derivatives Pricing, Trading and Strategies',
  'subjectCode': 'UCS658',
  'venue': 'LT102',
  'color': '#FFD700'},
 {'day': 'Wednesday',
  'hour': '6:00 PM',
  'subjectName': 'Derivatives Pricing, Trading and Strategies',
  'subjectCode': 'UCS658',
  'venue': 'LT102',
  'color': '#FFD700'},
 {'day': 'Monday',
  'hour': '8:00 AM',
  'subjectName': 'Microprocessor-Based Systems Design',
  'subjectCode': 'UCS617',
  'venue': 'ES-2',
  'color': '#90EE90'},
 {'day': 'Monday',
  'hour': '8:50 AM',
  'subjectName': 'Microprocessor-Based Systems Design',
  'subjectCode': 'UCS617',
  'venue': 'ES-2',
  'color': '#90EE90'},
 {'day': 'Monday',
  'hour': '3:30 PM',
  'subjectName': 'OPTIMIZATION TECHNIQUES',
  'subjectCode': 'UMA035',
  'venue': 'SS-1/(CSED)',
  'color': '#90EE90'},
 {'day': 'Monday',
  'hour': '4:20 PM',
  'subjectName': 'OPTIMIZATION TECHNIQUES',
  'subjectCode': 'UMA035',
  'venue': 'SS-1/(CSED)',
  'color': '#90EE90'},
 {'day': 'Monday',
  'hour': '5:10 PM',
  'subjectName': 'FINANCIAL MARKETS AND PORTFOLIO THEORY',
  'subjectCode': 'UCS657',
  'venue': 'DS-I',
  'color': '#90EE90'},
 {'day': 'Monday',
  'hour': '6:00 PM',
  'subjectName': 'FINANCIAL MARKETS AND PORTFOLIO THEORY',
  'subjectCode': 'UCS657',
  'venue': 'DS-I',
  'color': '#90EE90'},
 {'day': 'Tuesday',
  'hour': '11:20 AM',
  'subjectName': 'Computer Graphics',
  'subjectCode': 'UCS505',
  'venue': 'IS-2',
  'color': '#90EE90'},
 {'day': 'Tuesday',
  'hour': '12:10 PM',
  'subjectName': 'Computer Graphics',
  'subjectCode': 'UCS505',
  'venue': 'IS-2',
  'color': '#90EE90'},
 {'day': 'Tuesday',
  'hour': '5:10 PM',
  'subjectName': 'Derivatives Pricing, Trading and Strategies',
  'subjectCode': 'UCS658',
  'venue': 'DS-I',
  'color': '#90EE90'},
 {'day': 'Tuesday',
  'hour': '6:00 PM',
  'subjectName': 'Derivatives Pricing, Trading and Strategies',
  'subjectCode': 'UCS658',
  'venue': 'DS-I',
  'color': '#90EE90'},
 {'day': 'Tuesday',
  'hour': '1:50 PM',
  'subjectName': 'INNOVATION AND ENTREPRENEURSHIP',
  'subjectCode': 'UTA025',
  'venue': 'T201',
  'color': '#ADD8E6'},
 {'day': 'Tuesday',
  'hour': '2:40 PM',
  'subjectName': 'INNOVATION AND ENTREPRENEURSHIP',
  'subjectCode': 'UTA025',
  'venue': 'T201',
  'color': '#ADD8E6'},
 {'day': 'Friday',
  'hour': '3:30 PM',
  'subjectName': 'Theory of Computation',
  'subjectCode': 'UCS701',
  'venue': 'T202',
  'color': '#ADD8E6'},
 {'day': 'Monday',
  'hour': '9:40 AM',
  'subjectName': 'GPU Computing',
  'subjectCode': 'UCS635',
  'venue': 'LP109',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '10:30 AM',
  'subjectName': 'GPU Computing',
  'subjectCode': 'UCS635',
  'venue': 'LP109',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '1:50 PM',
  'subjectName': 'GPU Computing',
  'subjectCode': 'UCS635',
  'venue': 'IOT',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '2:40 PM',
  'subjectName': 'GPU Computing',
  'subjectCode': 'UCS635',
  'venue': 'IOT',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '9:40 AM',
  'subjectName': '3D Modelling and Animation',
  'subjectCode': 'UCS636',
  'venue': 'PGAS-II',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '10:30 AM',
  'subjectName': '3D Modelling and Animation',
  'subjectCode': 'UCS636',
  'venue': 'PGAS-II',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '1:50 PM',
  'subjectName': '3D Modelling and Animation',
  'subjectCode': 'UCS636',
  'venue': 'GA',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '2:40 PM',
  'subjectName': '3D Modelling and Animation',
  'subjectCode': 'UCS636',
  'venue': 'GA',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '9:40 AM',
  'subjectName': 'Cyber Forensics',
  'subjectCode': 'UCS648',
  'venue': 'LP108',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '10:30 AM',
  'subjectName': 'Cyber Forensics',
  'subjectCode': 'UCS648',
  'venue': 'LP108',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '3:30 PM',
  'subjectName': 'Cyber Forensics',
  'subjectCode': 'UCS648',
  'venue': '',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '4:20 PM',
  'subjectName': 'Cyber Forensics',
  'subjectCode': 'UCS648',
  'venue': '',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '9:40 AM',
  'subjectName': 'Edge AI and Robotics: Embedded Vision',
  'subjectCode': 'UCS671',
  'venue': 'LP110',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '11:20 AM',
  'subjectName': 'Edge AI and Robotics: Embedded Vision',
  'subjectCode': 'UCS671',
  'venue': 'LP110',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '1:50 PM',
  'subjectName': 'Edge AI and Robotics: Embedded Vision',
  'subjectCode': 'UCS671',
  'venue': 'PGAS-II',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '2:40 PM',
  'subjectName': 'Edge AI and Robotics: Embedded Vision',
  'subjectCode': 'UCS671',
  'venue': 'PGAS-II',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '9:40 AM',
  'subjectName': 'Build and Release Management',
  'subjectCode': 'UCS659',
  'venue': 'F109',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '10:30 AM',
  'subjectName': 'Build and Release Management',
  'subjectCode': 'UCS659',
  'venue': 'F109',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '1:50 PM',
  'subjectName': 'Build and Release Management',
  'subjectCode': 'UCS659',
  'venue': 'GC-I',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '2:40 PM',
  'subjectName': 'Build and Release Management',
  'subjectCode': 'UCS659',
  'venue': 'GC-I',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '9:40 AM',
  'subjectName': 'Ethical Hacking-1',
  'subjectCode': 'UCS673',
  'venue': 'F103',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '10:30 AM',
  'subjectName': 'Ethical Hacking-1',
  'subjectCode': 'UCS673',
  'venue': 'F103',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '1:50 PM',
  'subjectName': 'Ethical Hacking-1',
  'subjectCode': 'UCS673',
  'venue': 'NS-II',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '2:40 PM',
  'subjectName': 'Ethical Hacking-1',
  'subjectCode': 'UCS673',
  'venue': 'NS-II',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '9:40 AM',
  'subjectName': 'Matrix Computation',
  'subjectCode': 'UMC622',
  'venue': 'F110',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '10:30 AM',
  'subjectName': 'Matrix Computation',
  'subjectCode': 'UMC622',
  'venue': 'F110',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '1:50 PM',
  'subjectName': 'Matrix Computation',
  'subjectCode': 'UMC622',
  'venue': 'GC-II',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '2:40 PM',
  'subjectName': 'Matrix Computation',
  'subjectCode': 'UMC622',
  'venue': 'GC-II',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '9:40 AM',
  'subjectName': 'Data Engineering',
  'subjectCode': 'UCS677',
  'venue': 'LT103',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '10:30 AM',
  'subjectName': 'Data Engineering',
  'subjectCode': 'UCS677',
  'venue': 'LT103',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '3:30 PM',
  'subjectName': 'Data Engineering',
  'subjectCode': 'UCS677',
  'venue': 'DBMS-I',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '4:20 PM',
  'subjectName': 'Data Engineering',
  'subjectCode': 'UCS677',
  'venue': 'DBMS-I',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '9:40 AM',
  'subjectName': 'FINANCIAL MARKETS AND PORTFOLIO THEORY',
  'subjectCode': 'UCS657',
  'venue': 'LT102',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '10:30 AM',
  'subjectName': 'FINANCIAL MARKETS AND PORTFOLIO THEORY',
  'subjectCode': 'UCS657',
  'venue': 'LT102',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '9:40 AM',
  'subjectName': 'Conversational AI: Speech Processing & Synthesis',
  'subjectCode': 'UCS749',
  'venue': 'LT401',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '10:30 AM',
  'subjectName': 'Conversational AI: Speech Processing & Synthesis',
  'subjectCode': 'UCS749',
  'venue': 'LT401',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '3:30 PM',
  'subjectName': 'Conversational AI: Speech Processing & Synthesis',
  'subjectCode': 'UCS749',
  'venue': '',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '4:20 PM',
  'subjectName': 'Conversational AI: Speech Processing & Synthesis',
  'subjectCode': 'UCS749',
  'venue': '',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '9:40 AM',
  'subjectName': 'Predictive Analytics using Statistics',
  'subjectCode': 'UCS654',
  'venue': 'LT101',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '10:30 AM',
  'subjectName': 'Predictive Analytics using Statistics',
  'subjectCode': 'UCS654',
  'venue': 'LT101',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '3:30 PM',
  'subjectName': 'Predictive Analytics using Statistics',
  'subjectCode': 'UCS654',
  'venue': 'ML',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '4:20 PM',
  'subjectName': 'Predictive Analytics using Statistics',
  'subjectCode': 'UCS654',
  'venue': 'ML',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '10:30 AM',
  'subjectName': 'Parallel & Distributed Computing',
  'subjectCode': 'UCS645',
  'venue': 'LP109',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '11:20 AM',
  'subjectName': 'Parallel & Distributed Computing',
  'subjectCode': 'UCS645',
  'venue': 'LP109',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '3:30 PM',
  'subjectName': 'Parallel & Distributed Computing',
  'subjectCode': 'UCS645',
  'venue': 'IOT',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '4:20 PM',
  'subjectName': 'Parallel & Distributed Computing',
  'subjectCode': 'UCS645',
  'venue': 'IOT',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '10:30 AM',
  'subjectName': 'Game Design & Development',
  'subjectCode': 'UCS646',
  'venue': 'PGAS-II',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '11:20 AM',
  'subjectName': 'Game Design & Development',
  'subjectCode': 'UCS646',
  'venue': 'PGAS-II',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '3:30 PM',
  'subjectName': 'Game Design & Development',
  'subjectCode': 'UCS646',
  'venue': '',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '4:20 PM',
  'subjectName': 'Game Design & Development',
  'subjectCode': 'UCS646',
  'venue': '',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '10:30 AM',
  'subjectName': 'Edge AI and Robotics: Data Center Vision',
  'subjectCode': 'UCS668',
  'venue': 'LP110',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '10:30 AM',
  'subjectName': 'Edge AI and Robotics: Data Center Vision',
  'subjectCode': 'UCS668',
  'venue': 'LP110',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '3:30 PM',
  'subjectName': 'Edge AI and Robotics: Data Center Vision',
  'subjectCode': 'UCS668',
  'venue': '',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '4:20 PM',
  'subjectName': 'Edge AI and Robotics: Data Center Vision',
  'subjectCode': 'UCS668',
  'venue': '',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '10:30 AM',
  'subjectName': 'Continuous Integration and Continuous Deployment',
  'subjectCode': 'UCS660',
  'venue': 'F109',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '11:20 AM',
  'subjectName': 'Continuous Integration and Continuous Deployment',
  'subjectCode': 'UCS660',
  'venue': 'F109',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '3:30 PM',
  'subjectName': 'Continuous Integration and Continuous Deployment',
  'subjectCode': 'UCS660',
  'venue': '',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '4:20 PM',
  'subjectName': 'Continuous Integration and Continuous Deployment',
  'subjectCode': 'UCS660',
  'venue': '',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '10:30 AM',
  'subjectName': 'Ethical Hacking-II',
  'subjectCode': 'UCS674',
  'venue': 'F103',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '11:20 AM',
  'subjectName': 'Ethical Hacking-II',
  'subjectCode': 'UCS674',
  'venue': 'F103',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '3:30 PM',
  'subjectName': 'Ethical Hacking-II',
  'subjectCode': 'UCS674',
  'venue': '',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '4:20 PM',
  'subjectName': 'Ethical Hacking-II',
  'subjectCode': 'UCS674',
  'venue': '',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '10:30 AM',
  'subjectName': 'Financial Mathematics',
  'subjectCode': 'UMC632',
  'venue': 'F110',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '11:20 AM',
  'subjectName': 'Financial Mathematics',
  'subjectCode': 'UMC632',
  'venue': 'F110',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '3:30 PM',
  'subjectName': 'Financial Mathematics',
  'subjectCode': 'UMC632',
  'venue': '',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '4:20 PM',
  'subjectName': 'Financial Mathematics',
  'subjectCode': 'UMC632',
  'venue': '',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '10:30 AM',
  'subjectName': 'Test Automation',
  'subjectCode': 'UCS662',
  'venue': 'LT103',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '11:20 AM',
  'subjectName': 'Test Automation',
  'subjectCode': 'UCS662',
  'venue': 'LT103',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '1:50 PM',
  'subjectName': 'Test Automation',
  'subjectCode': 'UCS662',
  'venue': 'DBMS-I',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '2:40 PM',
  'subjectName': 'Test Automation',
  'subjectCode': 'UCS662',
  'venue': 'DBMS-I',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '10:30 AM',
  'subjectName': 'Conversational AI: Natural Language Processing',
  'subjectCode': 'UCS664',
  'venue': 'LT401',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '11:20 AM',
  'subjectName': 'Conversational AI: Natural Language Processing',
  'subjectCode': 'UCS664',
  'venue': 'LT401',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '1:50 PM',
  'subjectName': 'Conversational AI: Natural Language Processing',
  'subjectCode': 'UCS664',
  'venue': 'ES-II',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '2:40 PM',
  'subjectName': 'Conversational AI: Natural Language Processing',
  'subjectCode': 'UCS664',
  'venue': 'ES-II',
  'color': '#FFC0CB'},
 {'day': 'Monday',
  'hour': '10:30 AM',
  'subjectName': 'DATA SCIENCE APPLICATIONS:NLP, COMPUTER VISION AND IOT',
  'subjectCode': 'UCS672',
  'venue': 'LT101',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '11:20 AM',
  'subjectName': 'DATA SCIENCE APPLICATIONS:NLP, COMPUTER VISION AND IOT',
  'subjectCode': 'UCS672',
  'venue': 'LT101',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '1:50 PM',
  'subjectName': 'DATA SCIENCE APPLICATIONS:NLP, COMPUTER VISION AND IOT',
  'subjectCode': 'UCS672',
  'venue': 'ML',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '2:40 PM',
  'subjectName': 'DATA SCIENCE APPLICATIONS:NLP, COMPUTER VISION AND IOT',
  'subjectCode': 'UCS672',
  'venue': 'ML',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '10:30 AM',
  'subjectName': 'Secure Coding',
  'subjectCode': 'UCS638',
  'venue': 'LP108',
  'color': '#FFC0CB'},
 {'day': 'Thursday',
  'hour': '11:20 AM',
  'subjectName': 'Secure Coding',
  'subjectCode': 'UCS638',
  'venue': 'LP108',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '1:50 PM',
  'subjectName': 'Secure Coding',
  'subjectCode': 'UCS638',
  'venue': 'NS-I',
  'color': '#FFC0CB'},
 {'day': 'Wednesday',
  'hour': '2:40 PM',
  'subjectName': 'Secure Coding',
  'subjectCode': 'UCS638',
  'venue': 'NS-I',
  'color': '#FFC0CB'}];


const Timetable = () => {

    const getEvent = (day, hour) => {
      return events.find((event) => event.day === day && event.hour === hour);
    };

    console.log(getEvent('Monday', '9 AM'));


  return (
    <div className="timetable">
      <div className="cell header"></div>
      {hours.map((hour) => (
        <div key={hour} className="cell header">{hour}</div>
      ))}

      {days.map((day) => (
        <React.Fragment>
          <div className="cell header">{day}</div>

          {hours.map((hour) => {
            const event = getEvent(day, hour);
            return (
              <div className="cell" style={{ backgroundColor: event?.color || 'white' }}>
                <p className='subname'>{event ? event.subjectName : ''}</p>
                <p>{event ? event.subjectCode : ''}</p>
                <p>{event ? event.venue : ''}</p>
              </div>
            )
          })}
        </React.Fragment>
      ))}


    </div>
  );
};

export default Timetable;
